## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Boston + LinearRegression

In [4]:
boston = datasets.load_boston()

In [9]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [7]:
boston.target[:20]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2])

In [10]:
bx_train, bx_test, by_train, by_test = train_test_split( boston.data, boston.target, test_size=0.2, random_state=42)

In [11]:
regr = linear_model.LinearRegression()

In [15]:
regr.fit(bx_train, by_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
by_pred = regr.predict(bx_test)

In [18]:
print(regr.coef_)

[-1.12463481e-01  3.00810168e-02  4.07309919e-02  2.78676719e+00
 -1.72406347e+01  4.43248784e+00 -6.23998173e-03 -1.44848504e+00
  2.62113793e-01 -1.06390978e-02 -9.16398679e-01  1.24516469e-02
 -5.09349120e-01]


In [19]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(by_test, by_pred))

Mean squared error: 24.31


# Boston + LinearRegression + LASSO

In [27]:
lasso = linear_model.Lasso(alpha=10.0)


In [28]:
lasso.fit(bx_train, by_train)

Lasso(alpha=10.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [29]:
by_pred = lasso.predict(bx_test)

In [30]:
print(lasso.coef_)

[-0.          0.00632092 -0.          0.          0.          0.
  0.         -0.          0.         -0.0090727  -0.          0.00989229
 -0.6041477 ]


In [31]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(by_test, by_pred))

Mean squared error: 34.69


# Boston + LinearRegression + RIDGE

In [37]:
ridge = linear_model.Ridge(alpha=10.0)

In [38]:
ridge.fit(bx_train, by_train)

Ridge(alpha=10.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [39]:
by_pred = ridge.predict(bx_test)

In [40]:
print(ridge.coef_)

[-0.10631138  0.03552173 -0.02605121  1.81473024 -1.89295     4.19021435
 -0.01531845 -1.23258832  0.24752086 -0.0127395  -0.76226458  0.01293182
 -0.5626259 ]


In [41]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(by_test, by_pred))

Mean squared error: 24.67


# Wine + LinearRegression

In [42]:
wine = datasets.load_wine()

In [43]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [44]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [45]:
wx_train, wx_test, wy_train, wy_test = train_test_split(wine.data, wine.target, test_size = 0.2, random_state = 42)

In [47]:
log = linear_model.LogisticRegression()

In [48]:
log.fit(wx_train,wy_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [49]:
wy_pred = log.predict(wx_test)

In [50]:
print(log.coef_)

[[-4.70615079e-01  6.52347546e-01  1.15785090e+00 -5.93992936e-01
  -2.40023312e-02  1.22893836e-01  1.34792594e+00  1.21129343e-01
  -3.06783469e-01 -7.98210137e-02 -1.51671527e-01  7.16848837e-01
   1.41154000e-02]
 [ 8.05007177e-01 -1.09848493e+00 -8.53078985e-01  2.77644547e-01
   2.95986138e-03  6.31569211e-02  4.73161380e-01  2.72082698e-01
   6.91078294e-01 -1.78399305e+00  6.66512741e-01  3.35798140e-01
  -1.20384847e-02]
 [-2.59133928e-01  6.52310175e-01  1.20611748e-01  8.04321880e-02
   1.92407493e-02 -5.19182367e-01 -1.70239118e+00 -1.24123959e-01
  -7.08593520e-01  1.03220421e+00 -4.64782183e-01 -1.23780486e+00
  -5.56613356e-04]]


In [52]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(wy_test, wy_pred))

Mean squared error: 0.03


# Wine + LinearRegression + LASSO

In [54]:
wlasso = linear_model.Lasso(alpha=10)

In [55]:
wlasso.fit(wx_train,wy_train)

Lasso(alpha=10, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [56]:
wy_pred = wlasso.predict(wx_test)

In [57]:
print(wlasso.coef_)

[ 0.          0.          0.          0.          0.         -0.
 -0.          0.         -0.          0.         -0.         -0.
 -0.00148848]


In [58]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(wy_test, wy_pred))

Mean squared error: 0.32


# Wine + LinearRegression + RIDGE

In [74]:
wridge = linear_model.Ridge(alpha=10)

In [75]:
wridge.fit(wx_train,wy_train)

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [76]:
wy_pred = wridge.predict(wx_test)

In [77]:
print(wridge.coef_)

[-0.09694452  0.04258002 -0.10412025  0.03616954  0.00047244  0.02777076
 -0.27733556 -0.03300559 -0.00411121  0.08714487 -0.05033461 -0.21648142
 -0.00081243]


In [78]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(wy_test, wy_pred))

Mean squared error: 0.07
